/*
* generated by Xtext
*/
package de.htwg.scaltex.dsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ScalTeXOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
