/*
 * generated by Xtext
 */
package de.htwg.scaltex.latexdsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LaTeXDSLRuntimeModule extends de.htwg.scaltex.latexdsl.AbstractLaTeXDSLRuntimeModule {

}
