/*
* generated by Xtext
*/
package de.htwg.scaltex.dsl.ui.contentassist;

import de.htwg.scaltex.dsl.ui.contentassist.AbstractScalTeXProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ScalTeXProposalProvider extends AbstractScalTeXProposalProvider {

}
