grammar de.htwg.scaltex.dsl.ScalTeX with org.eclipse.xtext.xbase.Xbase

generate scalTeX "http://www.htwg.de/scaltex/dsl/ScalTeX"
import "http://www.eclipse.org/xtext/xbase/Xbase"

Script returns XBlockExpression:
  {Script} 
  // return an object of type Script which is a subtype of XBlockExpression
  ((expressions+=XExpressionInsideBlock | imports+=Import) ';'?)*;
 
Import:
  'import' importedNamespace=QualifiedNameWithWildcard;
 
QualifiedNameWithWildcard:
  QualifiedName '.*'?;