/*
 * generated by Xtext
 */
package de.htwg.scaltex.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ScalTeXRuntimeModule extends de.htwg.scaltex.dsl.AbstractScalTeXRuntimeModule {

}
