/*
 * generated by Xtext
 */
package de.htwg.scaltex.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ScalTeXUiModule extends de.htwg.scaltex.dsl.ui.AbstractScalTeXUiModule {
	public ScalTeXUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
