/*
 * generated by Xtext
 */
package de.htwg.scaltex.latexdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LaTeXDSLUiModule extends de.htwg.scaltex.latexdsl.ui.AbstractLaTeXDSLUiModule {
	public LaTeXDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
