/*
* generated by Xtext
*/
package de.htwg.scaltex.latexdsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LaTeXDSLOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
