/*
* generated by Xtext
*/
package de.htwg.scaltex.latexdsl.ui.contentassist;

import de.htwg.scaltex.latexdsl.ui.contentassist.AbstractLaTeXDSLProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LaTeXDSLProposalProvider extends AbstractLaTeXDSLProposalProvider {

}
